// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enums.proto

package enums

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Enum indicating builders used
type BuilderType int32

const (
	// Could not determine builder type
	BuilderType_UNKNOWN_BUILDER_TYPE BuilderType = 0
	// JIB Builder
	BuilderType_JIB BuilderType = 1
	// Bazel Builder
	BuilderType_BAZEL BuilderType = 2
	// Buildpacks Builder
	BuilderType_BUILDPACKS BuilderType = 3
	// Custom Builder
	BuilderType_CUSTOM BuilderType = 4
	// Kaniko Builder
	BuilderType_KANIKO BuilderType = 5
	// Docker Builder
	BuilderType_DOCKER BuilderType = 6
)

var BuilderType_name = map[int32]string{
	0: "UNKNOWN_BUILDER_TYPE",
	1: "JIB",
	2: "BAZEL",
	3: "BUILDPACKS",
	4: "CUSTOM",
	5: "KANIKO",
	6: "DOCKER",
}

var BuilderType_value = map[string]int32{
	"UNKNOWN_BUILDER_TYPE": 0,
	"JIB":                  1,
	"BAZEL":                2,
	"BUILDPACKS":           3,
	"CUSTOM":               4,
	"KANIKO":               5,
	"DOCKER":               6,
}

func (x BuilderType) String() string {
	return proto.EnumName(BuilderType_name, int32(x))
}

func (BuilderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_888b6bd9597961ff, []int{0}
}

// Enum indicating build type i.e. local, cluster vs GCB
type BuildType int32

const (
	// Could not determine Build Type
	BuildType_UNKNOWN_BUILD_TYPE BuildType = 0
	// Cluster Build
	BuildType_CLUSTER BuildType = 1
	// GCB Build
	BuildType_GCB BuildType = 2
	// Local Build
	BuildType_LOCAL BuildType = 3
)

var BuildType_name = map[int32]string{
	0: "UNKNOWN_BUILD_TYPE",
	1: "CLUSTER",
	2: "GCB",
	3: "LOCAL",
}

var BuildType_value = map[string]int32{
	"UNKNOWN_BUILD_TYPE": 0,
	"CLUSTER":            1,
	"GCB":                2,
	"LOCAL":              3,
}

func (x BuildType) String() string {
	return proto.EnumName(BuildType_name, int32(x))
}

func (BuildType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_888b6bd9597961ff, []int{1}
}

// Enum indicating test tools used
type TesterType int32

const (
	// Could not determine Test Type
	TesterType_UNKNOWN_TEST_TYPE TesterType = 0
	// Unit tests
	TesterType_UNIT TesterType = 1
	// Container Structure tests
	TesterType_CONTAINER_STRUCTURE_TEST TesterType = 2
)

var TesterType_name = map[int32]string{
	0: "UNKNOWN_TEST_TYPE",
	1: "UNIT",
	2: "CONTAINER_STRUCTURE_TEST",
}

var TesterType_value = map[string]int32{
	"UNKNOWN_TEST_TYPE":        0,
	"UNIT":                     1,
	"CONTAINER_STRUCTURE_TEST": 2,
}

func (x TesterType) String() string {
	return proto.EnumName(TesterType_name, int32(x))
}

func (TesterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_888b6bd9597961ff, []int{2}
}

// Enum indicating deploy tools used
type DeployerType int32

const (
	// Could not determine Deployer Type
	DeployerType_UNKNOWN_DEPLOYER_TYPE DeployerType = 0
	// Helm Deployer
	DeployerType_HELM DeployerType = 1
	// Kustomize Deployer
	DeployerType_KUSTOMIZE DeployerType = 2
	// Kubectl Deployer
	DeployerType_KUBECTL DeployerType = 3
)

var DeployerType_name = map[int32]string{
	0: "UNKNOWN_DEPLOYER_TYPE",
	1: "HELM",
	2: "KUSTOMIZE",
	3: "KUBECTL",
}

var DeployerType_value = map[string]int32{
	"UNKNOWN_DEPLOYER_TYPE": 0,
	"HELM":                  1,
	"KUSTOMIZE":             2,
	"KUBECTL":               3,
}

func (x DeployerType) String() string {
	return proto.EnumName(DeployerType_name, int32(x))
}

func (DeployerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_888b6bd9597961ff, []int{3}
}

// Enum indicating cluster type the application is deployed to
type ClusterType int32

const (
	// Could not determine Cluster Type
	ClusterType_UNKNOWN_CLUSTER_TYPE ClusterType = 0
	// Minikube Cluster
	ClusterType_MINIKUBE ClusterType = 1
	// GKE cluster
	ClusterType_GKE ClusterType = 2
	// All Cluster except Minikube and GKE
	ClusterType_OTHER ClusterType = 3
)

var ClusterType_name = map[int32]string{
	0: "UNKNOWN_CLUSTER_TYPE",
	1: "MINIKUBE",
	2: "GKE",
	3: "OTHER",
}

var ClusterType_value = map[string]int32{
	"UNKNOWN_CLUSTER_TYPE": 0,
	"MINIKUBE":             1,
	"GKE":                  2,
	"OTHER":                3,
}

func (x ClusterType) String() string {
	return proto.EnumName(ClusterType_name, int32(x))
}

func (ClusterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_888b6bd9597961ff, []int{4}
}

// Enum indicating the log level of a line of output
type LogLevel int32

const (
	// Debug Level
	LogLevel_DEBUG LogLevel = 0
	// Info Level
	LogLevel_INFO LogLevel = 1
	// Warn Level
	LogLevel_WARN LogLevel = 2
	// Error Level
	LogLevel_ERROR LogLevel = 3
	// Fatal Level
	LogLevel_FATAL LogLevel = 4
	// Panic Level
	LogLevel_PANIC LogLevel = 5
)

var LogLevel_name = map[int32]string{
	0: "DEBUG",
	1: "INFO",
	2: "WARN",
	3: "ERROR",
	4: "FATAL",
	5: "PANIC",
}

var LogLevel_value = map[string]int32{
	"DEBUG": 0,
	"INFO":  1,
	"WARN":  2,
	"ERROR": 3,
	"FATAL": 4,
	"PANIC": 5,
}

func (x LogLevel) String() string {
	return proto.EnumName(LogLevel_name, int32(x))
}

func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_888b6bd9597961ff, []int{5}
}

// Enum for Status codes<br>
// These error codes are prepended by Phase Name e.g.
// INIT, BUILD, TEST, DEPLOY, STATUSCHECK, DEVINIT<br>
// For Success Error codes, use range 200 to 250.<br>
// For Unknown error codes, use range 500 to 600.<br>
// For Cancelled Error code, use range 800 to 850.<br>
type StatusCode int32

const (
	// A default status code for events that do not have an associated phase.
	// Typically seen with the DevEndEvent event on success.
	StatusCode_OK StatusCode = 0
	// Status Check Success
	StatusCode_STATUSCHECK_SUCCESS StatusCode = 200
	// Build Success
	StatusCode_BUILD_SUCCESS StatusCode = 201
	// Deploy Success
	StatusCode_DEPLOY_SUCCESS StatusCode = 202
	// Test Success
	StatusCode_TEST_SUCCESS StatusCode = 203
	// Build error due to push access denied
	StatusCode_BUILD_PUSH_ACCESS_DENIED StatusCode = 101
	// Build error due to GCP project not found.
	StatusCode_BUILD_PROJECT_NOT_FOUND StatusCode = 102
	// Docker build error due to docker daemon not running
	StatusCode_BUILD_DOCKER_DAEMON_NOT_RUNNING StatusCode = 103
	// Build error due to user application code, e.g. compilation error, dockerfile error etc
	StatusCode_BUILD_USER_ERROR StatusCode = 104
	// Build error due to docker not available
	StatusCode_BUILD_DOCKER_UNAVAILABLE StatusCode = 105
	// Docker build error due to user not authorized to perform the action
	StatusCode_BUILD_DOCKER_UNAUTHORIZED StatusCode = 106
	// Docker system build error
	StatusCode_BUILD_DOCKER_SYSTEM_ERR StatusCode = 107
	// Docker build error due to Docker build container is already in the desired state
	StatusCode_BUILD_DOCKER_NOT_MODIFIED_ERR StatusCode = 108
	// Docker build error indicating a feature not supported
	StatusCode_BUILD_DOCKER_NOT_IMPLEMENTED_ERR StatusCode = 109
	// Docker build error indicates that for given build, data was lost or there is data corruption
	StatusCode_BUILD_DOCKER_DATA_LOSS_ERR StatusCode = 110
	// Docker build error indicates user is forbidden to perform the build or step/action.
	StatusCode_BUILD_DOCKER_FORBIDDEN_ERR StatusCode = 111
	// Docker build error due to some internal error and docker container state conflicts with the requested action and can't be performed
	StatusCode_BUILD_DOCKER_CONFLICT_ERR StatusCode = 112
	// Docker build error indicates the requested object does not exist
	StatusCode_BUILD_DOCKER_ERROR_NOT_FOUND StatusCode = 113
	// Docker build error indication invalid parameter sent to docker command
	StatusCode_BUILD_DOCKER_INVALID_PARAM_ERR StatusCode = 114
	// Docker build failed due to dockerfile not found
	StatusCode_BUILD_DOCKERFILE_NOT_FOUND StatusCode = 115
	// Docker build failed due `cacheFrom` user config error
	StatusCode_BUILD_DOCKER_CACHE_FROM_PULL_ERR StatusCode = 116
	// Build error due to digest for built artifact could not be retrieved from docker daemon.
	StatusCode_BUILD_DOCKER_GET_DIGEST_ERR StatusCode = 117
	// Build error due to digest for built artifact could not be retrieved from registry.
	StatusCode_BUILD_REGISTRY_GET_DIGEST_ERR StatusCode = 118
	// Build error indicating unknown Jib plugin type. Should be one of [maven, gradle]
	StatusCode_BUILD_UNKNOWN_JIB_PLUGIN_TYPE StatusCode = 119
	// Build error determining dependency for jib gradle project.
	StatusCode_BUILD_JIB_GRADLE_DEP_ERR StatusCode = 120
	// Build error determining dependency for jib gradle project.
	StatusCode_BUILD_JIB_MAVEN_DEP_ERR StatusCode = 121
	// Docker build error when listing containers.
	StatusCode_INIT_DOCKER_NETWORK_LISTING_CONTAINERS StatusCode = 122
	// Docker build error indicating an invalid container name (or id).
	StatusCode_INIT_DOCKER_NETWORK_INVALID_CONTAINER_NAME StatusCode = 123
	// Docker build error indicating the container referenced does not exists in the docker context used.
	StatusCode_INIT_DOCKER_NETWORK_CONTAINER_DOES_NOT_EXIST StatusCode = 124
	// Docker Network invalid mode
	StatusCode_INIT_DOCKER_NETWORK_INVALID_MODE StatusCode = 125
	// Error parsing Docker Network mode
	StatusCode_INIT_DOCKER_NETWORK_PARSE_ERR StatusCode = 126
	// Container image pull error
	StatusCode_STATUSCHECK_IMAGE_PULL_ERR StatusCode = 300
	// Container creating error
	StatusCode_STATUSCHECK_CONTAINER_CREATING StatusCode = 301
	// Container run error
	StatusCode_STATUSCHECK_RUN_CONTAINER_ERR StatusCode = 302
	// Container is already terminated
	StatusCode_STATUSCHECK_CONTAINER_TERMINATED StatusCode = 303
	// Deployment waiting for rollout
	StatusCode_STATUSCHECK_DEPLOYMENT_ROLLOUT_PENDING StatusCode = 304
	// Statefulset waiting for rollout
	StatusCode_STATUSCHECK_STATEFULSET_ROLLOUT_PENDING StatusCode = 305
	// Container restarting error
	StatusCode_STATUSCHECK_CONTAINER_RESTARTING StatusCode = 356
	// Readiness probe failed
	StatusCode_STATUSCHECK_UNHEALTHY StatusCode = 357
	// Node memory pressure error
	StatusCode_STATUSCHECK_NODE_MEMORY_PRESSURE StatusCode = 400
	// Node disk pressure error
	StatusCode_STATUSCHECK_NODE_DISK_PRESSURE StatusCode = 401
	// Node network unavailable error
	StatusCode_STATUSCHECK_NODE_NETWORK_UNAVAILABLE StatusCode = 402
	// Node PID pressure error
	StatusCode_STATUSCHECK_NODE_PID_PRESSURE StatusCode = 403
	// Node unschedulable error
	StatusCode_STATUSCHECK_NODE_UNSCHEDULABLE StatusCode = 404
	// Node unreachable error
	StatusCode_STATUSCHECK_NODE_UNREACHABLE StatusCode = 405
	// Node not ready error
	StatusCode_STATUSCHECK_NODE_NOT_READY StatusCode = 406
	// Scheduler failure error
	StatusCode_STATUSCHECK_FAILED_SCHEDULING StatusCode = 407
	// Kubectl connection error
	StatusCode_STATUSCHECK_KUBECTL_CONNECTION_ERR StatusCode = 409
	// Kubectl process killed error
	StatusCode_STATUSCHECK_KUBECTL_PID_KILLED StatusCode = 410
	// Kubectl client fetch err
	StatusCode_STATUSCHECK_KUBECTL_CLIENT_FETCH_ERR StatusCode = 411
	StatusCode_STATUSCHECK_DEPLOYMENT_FETCH_ERR     StatusCode = 412
	StatusCode_STATUSCHECK_STATEFULSET_FETCH_ERR    StatusCode = 413
	// Pod Initializing
	StatusCode_STATUSCHECK_POD_INITIALIZING StatusCode = 451
	// Could not determine error and phase
	StatusCode_UNKNOWN_ERROR StatusCode = 500
	// Status Check error unknown
	StatusCode_STATUSCHECK_UNKNOWN StatusCode = 501
	// Container is unschedulable due to unknown reasons
	StatusCode_STATUSCHECK_UNKNOWN_UNSCHEDULABLE StatusCode = 502
	// Container is waiting due to unknown reason
	StatusCode_STATUSCHECK_CONTAINER_WAITING_UNKNOWN StatusCode = 503
	// Container event reason unknown
	StatusCode_STATUSCHECK_UNKNOWN_EVENT StatusCode = 509
	// Deploy failed due to unknown reason
	StatusCode_DEPLOY_UNKNOWN StatusCode = 504
	// SYNC failed due to known reason
	StatusCode_SYNC_UNKNOWN StatusCode = 505
	// Build failed due to unknown reason
	StatusCode_BUILD_UNKNOWN StatusCode = 506
	// Dev Init failed due to unknown reason
	StatusCode_DEVINIT_UNKNOWN StatusCode = 507
	// Cleanup failed due to unknown reason
	StatusCode_CLEANUP_UNKNOWN StatusCode = 508
	// Initialization of the Skaffold session failed due to unknown reason(s)
	StatusCode_INIT_UNKNOWN StatusCode = 510
	// Build failed due to docker unknown error
	StatusCode_BUILD_DOCKER_UNKNOWN StatusCode = 511
	// Test failed due to unknown reason
	StatusCode_TEST_UNKNOWN StatusCode = 512
	// File Sync Initialize failure
	StatusCode_SYNC_INIT_ERROR StatusCode = 601
	// Failed to configure watcher for build dependencies in dev loop
	StatusCode_DEVINIT_REGISTER_BUILD_DEPS StatusCode = 701
	// Failed to configure watcher for test dependencies in dev loop
	StatusCode_DEVINIT_REGISTER_TEST_DEPS StatusCode = 702
	// Failed to configure watcher for deploy dependencies in dev loop
	StatusCode_DEVINIT_REGISTER_DEPLOY_DEPS StatusCode = 703
	// Failed to configure watcher for Skaffold configuration file.
	StatusCode_DEVINIT_REGISTER_CONFIG_DEP StatusCode = 704
	// Failed to configure watcher for build dependencies for a base image with v1 manifest.
	StatusCode_DEVINIT_UNSUPPORTED_V1_MANIFEST StatusCode = 705
	// User cancelled the skaffold dev run
	StatusCode_STATUSCHECK_USER_CANCELLED StatusCode = 800
	// Deadline for status check exceeded
	StatusCode_STATUSCHECK_DEADLINE_EXCEEDED StatusCode = 801
	// Build Cancelled
	StatusCode_BUILD_CANCELLED StatusCode = 802
	// Deploy cancelled due to user cancellation or one or more deployers failed.
	StatusCode_DEPLOY_CANCELLED StatusCode = 803
	// Docker build cancelled.
	StatusCode_BUILD_DOCKER_CANCELLED StatusCode = 804
	// Build error due to docker deadline was reached before the docker action completed
	StatusCode_BUILD_DOCKER_DEADLINE StatusCode = 805
	// Skaffold was unable to create the configured tagger
	StatusCode_INIT_CREATE_TAGGER_ERROR StatusCode = 901
	// Skaffold was unable to start as Minikube appears to be paused
	StatusCode_INIT_MINIKUBE_PAUSED_ERROR StatusCode = 902
	// Skaffold was unable to start as Minikube appears to be stopped
	StatusCode_INIT_MINIKUBE_NOT_RUNNING_ERROR StatusCode = 903
	// Skaffold was unable to create a configured image builder
	StatusCode_INIT_CREATE_BUILDER_ERROR StatusCode = 904
	// Skaffold was unable to create a configured deployer
	StatusCode_INIT_CREATE_DEPLOYER_ERROR StatusCode = 905
	// Skaffold was unable to create a configured test
	StatusCode_INIT_CREATE_TEST_DEP_ERROR StatusCode = 906
	// Skaffold encountered an error validating the artifact cache
	StatusCode_INIT_CACHE_ERROR StatusCode = 907
	// Skaffold encountered an error when configuring file watching
	StatusCode_INIT_CREATE_WATCH_TRIGGER_ERROR StatusCode = 908
	// Skaffold encountered an error when evaluating artifact dependencies
	StatusCode_INIT_CREATE_ARTIFACT_DEP_ERROR StatusCode = 909
	// Unable to connect to cluster
	StatusCode_DEPLOY_CLUSTER_CONNECTION_ERR StatusCode = 1001
	// Could not retrieve debug helpers.
	StatusCode_DEPLOY_DEBUG_HELPER_RETRIEVE_ERR StatusCode = 1002
	// Deploy clean up error
	StatusCode_DEPLOY_CLEANUP_ERR StatusCode = 1003
	// Unable to apply helm labels.
	StatusCode_DEPLOY_HELM_APPLY_LABELS StatusCode = 1004
	// Deploy error due to user deploy config for helm deployer
	StatusCode_DEPLOY_HELM_USER_ERR StatusCode = 1005
	// Helm error when no build result is found of value  specified in helm `artifactOverrides`
	StatusCode_DEPLOY_NO_MATCHING_BUILD StatusCode = 1006
	// Unable to get helm client version
	StatusCode_DEPLOY_HELM_VERSION_ERR StatusCode = 1007
	// Helm version not supported.
	StatusCode_DEPLOY_HELM_MIN_VERSION_ERR StatusCode = 1008
	// Unable to retrieve kubectl version
	StatusCode_DEPLOY_KUBECTL_VERSION_ERR StatusCode = 1109
	// User specified offline mode for rendering but remote manifests presents.
	StatusCode_DEPLOY_KUBECTL_OFFLINE_MODE_ERR StatusCode = 1010
	// Error waiting for previous version deletion before next version is active.
	StatusCode_DEPLOY_ERR_WAITING_FOR_DELETION StatusCode = 1011
	// Error reading manifests
	StatusCode_DEPLOY_READ_MANIFEST_ERR StatusCode = 1012
	// Error reading remote manifests
	StatusCode_DEPLOY_READ_REMOTE_MANIFEST_ERR StatusCode = 1013
	// Errors listing manifests
	StatusCode_DEPLOY_LIST_MANIFEST_ERR StatusCode = 1014
	// Deploy error due to user deploy config for kubectl deployer
	StatusCode_DEPLOY_KUBECTL_USER_ERR StatusCode = 1015
	// Deploy error due to user deploy config for kustomize deployer
	StatusCode_DEPLOY_KUSTOMIZE_USER_ERR StatusCode = 1016
	// Error replacing a built artifact in the manifests
	StatusCode_DEPLOY_REPLACE_IMAGE_ERR StatusCode = 1017
	// Error transforming a manifest during skaffold debug
	StatusCode_DEPLOY_TRANSFORM_MANIFEST_ERR StatusCode = 1018
	// Error setting user specified additional labels.
	StatusCode_DEPLOY_SET_LABEL_ERR StatusCode = 1019
	// Error writing hydrated kubernetes manifests.
	StatusCode_DEPLOY_MANIFEST_WRITE_ERR StatusCode = 1020
	// Error getting images from a kubernetes manifest.
	StatusCode_DEPLOY_PARSE_MANIFEST_IMAGES_ERR StatusCode = 1021
	// Helm config `createNamespace` not available
	StatusCode_DEPLOY_HELM_CREATE_NS_NOT_AVAILABLE StatusCode = 1022
	// Error expanding paths
	StatusCode_TEST_USER_CONFIG_ERR StatusCode = 1101
	// Error running container-structure-test
	StatusCode_TEST_CST_USER_ERR StatusCode = 1102
	// Unable to docker pull image
	StatusCode_TEST_IMG_PULL_ERR StatusCode = 1103
	// Unable to parse test command
	StatusCode_TEST_CUSTOM_CMD_PARSE_ERR StatusCode = 1104
	// Command returned non-zero exit code
	StatusCode_TEST_CUSTOM_CMD_RUN_NON_ZERO_EXIT_ERR StatusCode = 1105
	// command cancelled or timed out
	StatusCode_TEST_CUSTOM_CMD_RUN_TIMEDOUT_ERR StatusCode = 1106
	// command cancelled or timed out
	StatusCode_TEST_CUSTOM_CMD_RUN_CANCELLED_ERR StatusCode = 1107
	// command context error
	StatusCode_TEST_CUSTOM_CMD_RUN_EXECUTION_ERR StatusCode = 1108
	// command exited
	StatusCode_TEST_CUSTOM_CMD_RUN_EXITED_ERR StatusCode = 1110
	// error running cmd
	StatusCode_TEST_CUSTOM_CMD_RUN_ERR StatusCode = 1111
	// Error getting dependencies from command
	StatusCode_TEST_CUSTOM_DEPENDENCIES_CMD_ERR StatusCode = 1112
	// Unmarshalling dependency output error
	StatusCode_TEST_CUSTOM_DEPENDENCIES_UNMARSHALL_ERR StatusCode = 1113
	// Error retrieving the command
	StatusCode_TEST_CUSTOM_CMD_RETRIEVE_ERR StatusCode = 1114
	// Catch-all configuration file parsing error
	StatusCode_CONFIG_FILE_PARSING_ERR StatusCode = 1201
	// Main configuration file not found
	StatusCode_CONFIG_FILE_NOT_FOUND_ERR StatusCode = 1202
	// Dependency configuration file not found
	StatusCode_CONFIG_DEPENDENCY_NOT_FOUND_ERR StatusCode = 1203
	// Duplicate config names in the same configuration file
	StatusCode_CONFIG_DUPLICATE_NAMES_SAME_FILE_ERR StatusCode = 1204
	// Duplicate config names in two configuration files
	StatusCode_CONFIG_DUPLICATE_NAMES_ACROSS_FILES_ERR StatusCode = 1205
	// No configs matching configs filter
	StatusCode_CONFIG_BAD_FILTER_ERR StatusCode = 1206
	// No configs parsed from current file
	StatusCode_CONFIG_ZERO_FOUND_ERR StatusCode = 1207
	// Failed to apply profiles to config
	StatusCode_CONFIG_APPLY_PROFILES_ERR StatusCode = 1208
	// Failed to set default config values
	StatusCode_CONFIG_DEFAULT_VALUES_ERR StatusCode = 1209
	// Failed to substitute absolute file paths in config
	StatusCode_CONFIG_FILE_PATHS_SUBSTITUTION_ERR StatusCode = 1210
	// Same config imported at least twice with different set of profiles
	StatusCode_CONFIG_MULTI_IMPORT_PROFILE_CONFLICT_ERR StatusCode = 1211
)

var StatusCode_name = map[int32]string{
	0:    "OK",
	200:  "STATUSCHECK_SUCCESS",
	201:  "BUILD_SUCCESS",
	202:  "DEPLOY_SUCCESS",
	203:  "TEST_SUCCESS",
	101:  "BUILD_PUSH_ACCESS_DENIED",
	102:  "BUILD_PROJECT_NOT_FOUND",
	103:  "BUILD_DOCKER_DAEMON_NOT_RUNNING",
	104:  "BUILD_USER_ERROR",
	105:  "BUILD_DOCKER_UNAVAILABLE",
	106:  "BUILD_DOCKER_UNAUTHORIZED",
	107:  "BUILD_DOCKER_SYSTEM_ERR",
	108:  "BUILD_DOCKER_NOT_MODIFIED_ERR",
	109:  "BUILD_DOCKER_NOT_IMPLEMENTED_ERR",
	110:  "BUILD_DOCKER_DATA_LOSS_ERR",
	111:  "BUILD_DOCKER_FORBIDDEN_ERR",
	112:  "BUILD_DOCKER_CONFLICT_ERR",
	113:  "BUILD_DOCKER_ERROR_NOT_FOUND",
	114:  "BUILD_DOCKER_INVALID_PARAM_ERR",
	115:  "BUILD_DOCKERFILE_NOT_FOUND",
	116:  "BUILD_DOCKER_CACHE_FROM_PULL_ERR",
	117:  "BUILD_DOCKER_GET_DIGEST_ERR",
	118:  "BUILD_REGISTRY_GET_DIGEST_ERR",
	119:  "BUILD_UNKNOWN_JIB_PLUGIN_TYPE",
	120:  "BUILD_JIB_GRADLE_DEP_ERR",
	121:  "BUILD_JIB_MAVEN_DEP_ERR",
	122:  "INIT_DOCKER_NETWORK_LISTING_CONTAINERS",
	123:  "INIT_DOCKER_NETWORK_INVALID_CONTAINER_NAME",
	124:  "INIT_DOCKER_NETWORK_CONTAINER_DOES_NOT_EXIST",
	125:  "INIT_DOCKER_NETWORK_INVALID_MODE",
	126:  "INIT_DOCKER_NETWORK_PARSE_ERR",
	300:  "STATUSCHECK_IMAGE_PULL_ERR",
	301:  "STATUSCHECK_CONTAINER_CREATING",
	302:  "STATUSCHECK_RUN_CONTAINER_ERR",
	303:  "STATUSCHECK_CONTAINER_TERMINATED",
	304:  "STATUSCHECK_DEPLOYMENT_ROLLOUT_PENDING",
	305:  "STATUSCHECK_STATEFULSET_ROLLOUT_PENDING",
	356:  "STATUSCHECK_CONTAINER_RESTARTING",
	357:  "STATUSCHECK_UNHEALTHY",
	400:  "STATUSCHECK_NODE_MEMORY_PRESSURE",
	401:  "STATUSCHECK_NODE_DISK_PRESSURE",
	402:  "STATUSCHECK_NODE_NETWORK_UNAVAILABLE",
	403:  "STATUSCHECK_NODE_PID_PRESSURE",
	404:  "STATUSCHECK_NODE_UNSCHEDULABLE",
	405:  "STATUSCHECK_NODE_UNREACHABLE",
	406:  "STATUSCHECK_NODE_NOT_READY",
	407:  "STATUSCHECK_FAILED_SCHEDULING",
	409:  "STATUSCHECK_KUBECTL_CONNECTION_ERR",
	410:  "STATUSCHECK_KUBECTL_PID_KILLED",
	411:  "STATUSCHECK_KUBECTL_CLIENT_FETCH_ERR",
	412:  "STATUSCHECK_DEPLOYMENT_FETCH_ERR",
	413:  "STATUSCHECK_STATEFULSET_FETCH_ERR",
	451:  "STATUSCHECK_POD_INITIALIZING",
	500:  "UNKNOWN_ERROR",
	501:  "STATUSCHECK_UNKNOWN",
	502:  "STATUSCHECK_UNKNOWN_UNSCHEDULABLE",
	503:  "STATUSCHECK_CONTAINER_WAITING_UNKNOWN",
	509:  "STATUSCHECK_UNKNOWN_EVENT",
	504:  "DEPLOY_UNKNOWN",
	505:  "SYNC_UNKNOWN",
	506:  "BUILD_UNKNOWN",
	507:  "DEVINIT_UNKNOWN",
	508:  "CLEANUP_UNKNOWN",
	510:  "INIT_UNKNOWN",
	511:  "BUILD_DOCKER_UNKNOWN",
	512:  "TEST_UNKNOWN",
	601:  "SYNC_INIT_ERROR",
	701:  "DEVINIT_REGISTER_BUILD_DEPS",
	702:  "DEVINIT_REGISTER_TEST_DEPS",
	703:  "DEVINIT_REGISTER_DEPLOY_DEPS",
	704:  "DEVINIT_REGISTER_CONFIG_DEP",
	705:  "DEVINIT_UNSUPPORTED_V1_MANIFEST",
	800:  "STATUSCHECK_USER_CANCELLED",
	801:  "STATUSCHECK_DEADLINE_EXCEEDED",
	802:  "BUILD_CANCELLED",
	803:  "DEPLOY_CANCELLED",
	804:  "BUILD_DOCKER_CANCELLED",
	805:  "BUILD_DOCKER_DEADLINE",
	901:  "INIT_CREATE_TAGGER_ERROR",
	902:  "INIT_MINIKUBE_PAUSED_ERROR",
	903:  "INIT_MINIKUBE_NOT_RUNNING_ERROR",
	904:  "INIT_CREATE_BUILDER_ERROR",
	905:  "INIT_CREATE_DEPLOYER_ERROR",
	906:  "INIT_CREATE_TEST_DEP_ERROR",
	907:  "INIT_CACHE_ERROR",
	908:  "INIT_CREATE_WATCH_TRIGGER_ERROR",
	909:  "INIT_CREATE_ARTIFACT_DEP_ERROR",
	1001: "DEPLOY_CLUSTER_CONNECTION_ERR",
	1002: "DEPLOY_DEBUG_HELPER_RETRIEVE_ERR",
	1003: "DEPLOY_CLEANUP_ERR",
	1004: "DEPLOY_HELM_APPLY_LABELS",
	1005: "DEPLOY_HELM_USER_ERR",
	1006: "DEPLOY_NO_MATCHING_BUILD",
	1007: "DEPLOY_HELM_VERSION_ERR",
	1008: "DEPLOY_HELM_MIN_VERSION_ERR",
	1109: "DEPLOY_KUBECTL_VERSION_ERR",
	1010: "DEPLOY_KUBECTL_OFFLINE_MODE_ERR",
	1011: "DEPLOY_ERR_WAITING_FOR_DELETION",
	1012: "DEPLOY_READ_MANIFEST_ERR",
	1013: "DEPLOY_READ_REMOTE_MANIFEST_ERR",
	1014: "DEPLOY_LIST_MANIFEST_ERR",
	1015: "DEPLOY_KUBECTL_USER_ERR",
	1016: "DEPLOY_KUSTOMIZE_USER_ERR",
	1017: "DEPLOY_REPLACE_IMAGE_ERR",
	1018: "DEPLOY_TRANSFORM_MANIFEST_ERR",
	1019: "DEPLOY_SET_LABEL_ERR",
	1020: "DEPLOY_MANIFEST_WRITE_ERR",
	1021: "DEPLOY_PARSE_MANIFEST_IMAGES_ERR",
	1022: "DEPLOY_HELM_CREATE_NS_NOT_AVAILABLE",
	1101: "TEST_USER_CONFIG_ERR",
	1102: "TEST_CST_USER_ERR",
	1103: "TEST_IMG_PULL_ERR",
	1104: "TEST_CUSTOM_CMD_PARSE_ERR",
	1105: "TEST_CUSTOM_CMD_RUN_NON_ZERO_EXIT_ERR",
	1106: "TEST_CUSTOM_CMD_RUN_TIMEDOUT_ERR",
	1107: "TEST_CUSTOM_CMD_RUN_CANCELLED_ERR",
	1108: "TEST_CUSTOM_CMD_RUN_EXECUTION_ERR",
	1110: "TEST_CUSTOM_CMD_RUN_EXITED_ERR",
	1111: "TEST_CUSTOM_CMD_RUN_ERR",
	1112: "TEST_CUSTOM_DEPENDENCIES_CMD_ERR",
	1113: "TEST_CUSTOM_DEPENDENCIES_UNMARSHALL_ERR",
	1114: "TEST_CUSTOM_CMD_RETRIEVE_ERR",
	1201: "CONFIG_FILE_PARSING_ERR",
	1202: "CONFIG_FILE_NOT_FOUND_ERR",
	1203: "CONFIG_DEPENDENCY_NOT_FOUND_ERR",
	1204: "CONFIG_DUPLICATE_NAMES_SAME_FILE_ERR",
	1205: "CONFIG_DUPLICATE_NAMES_ACROSS_FILES_ERR",
	1206: "CONFIG_BAD_FILTER_ERR",
	1207: "CONFIG_ZERO_FOUND_ERR",
	1208: "CONFIG_APPLY_PROFILES_ERR",
	1209: "CONFIG_DEFAULT_VALUES_ERR",
	1210: "CONFIG_FILE_PATHS_SUBSTITUTION_ERR",
	1211: "CONFIG_MULTI_IMPORT_PROFILE_CONFLICT_ERR",
}

var StatusCode_value = map[string]int32{
	"OK":                                           0,
	"STATUSCHECK_SUCCESS":                          200,
	"BUILD_SUCCESS":                                201,
	"DEPLOY_SUCCESS":                               202,
	"TEST_SUCCESS":                                 203,
	"BUILD_PUSH_ACCESS_DENIED":                     101,
	"BUILD_PROJECT_NOT_FOUND":                      102,
	"BUILD_DOCKER_DAEMON_NOT_RUNNING":              103,
	"BUILD_USER_ERROR":                             104,
	"BUILD_DOCKER_UNAVAILABLE":                     105,
	"BUILD_DOCKER_UNAUTHORIZED":                    106,
	"BUILD_DOCKER_SYSTEM_ERR":                      107,
	"BUILD_DOCKER_NOT_MODIFIED_ERR":                108,
	"BUILD_DOCKER_NOT_IMPLEMENTED_ERR":             109,
	"BUILD_DOCKER_DATA_LOSS_ERR":                   110,
	"BUILD_DOCKER_FORBIDDEN_ERR":                   111,
	"BUILD_DOCKER_CONFLICT_ERR":                    112,
	"BUILD_DOCKER_ERROR_NOT_FOUND":                 113,
	"BUILD_DOCKER_INVALID_PARAM_ERR":               114,
	"BUILD_DOCKERFILE_NOT_FOUND":                   115,
	"BUILD_DOCKER_CACHE_FROM_PULL_ERR":             116,
	"BUILD_DOCKER_GET_DIGEST_ERR":                  117,
	"BUILD_REGISTRY_GET_DIGEST_ERR":                118,
	"BUILD_UNKNOWN_JIB_PLUGIN_TYPE":                119,
	"BUILD_JIB_GRADLE_DEP_ERR":                     120,
	"BUILD_JIB_MAVEN_DEP_ERR":                      121,
	"INIT_DOCKER_NETWORK_LISTING_CONTAINERS":       122,
	"INIT_DOCKER_NETWORK_INVALID_CONTAINER_NAME":   123,
	"INIT_DOCKER_NETWORK_CONTAINER_DOES_NOT_EXIST": 124,
	"INIT_DOCKER_NETWORK_INVALID_MODE":             125,
	"INIT_DOCKER_NETWORK_PARSE_ERR":                126,
	"STATUSCHECK_IMAGE_PULL_ERR":                   300,
	"STATUSCHECK_CONTAINER_CREATING":               301,
	"STATUSCHECK_RUN_CONTAINER_ERR":                302,
	"STATUSCHECK_CONTAINER_TERMINATED":             303,
	"STATUSCHECK_DEPLOYMENT_ROLLOUT_PENDING":       304,
	"STATUSCHECK_STATEFULSET_ROLLOUT_PENDING":      305,
	"STATUSCHECK_CONTAINER_RESTARTING":             356,
	"STATUSCHECK_UNHEALTHY":                        357,
	"STATUSCHECK_NODE_MEMORY_PRESSURE":             400,
	"STATUSCHECK_NODE_DISK_PRESSURE":               401,
	"STATUSCHECK_NODE_NETWORK_UNAVAILABLE":         402,
	"STATUSCHECK_NODE_PID_PRESSURE":                403,
	"STATUSCHECK_NODE_UNSCHEDULABLE":               404,
	"STATUSCHECK_NODE_UNREACHABLE":                 405,
	"STATUSCHECK_NODE_NOT_READY":                   406,
	"STATUSCHECK_FAILED_SCHEDULING":                407,
	"STATUSCHECK_KUBECTL_CONNECTION_ERR":           409,
	"STATUSCHECK_KUBECTL_PID_KILLED":               410,
	"STATUSCHECK_KUBECTL_CLIENT_FETCH_ERR":         411,
	"STATUSCHECK_DEPLOYMENT_FETCH_ERR":             412,
	"STATUSCHECK_STATEFULSET_FETCH_ERR":            413,
	"STATUSCHECK_POD_INITIALIZING":                 451,
	"UNKNOWN_ERROR":                                500,
	"STATUSCHECK_UNKNOWN":                          501,
	"STATUSCHECK_UNKNOWN_UNSCHEDULABLE":            502,
	"STATUSCHECK_CONTAINER_WAITING_UNKNOWN":        503,
	"STATUSCHECK_UNKNOWN_EVENT":                    509,
	"DEPLOY_UNKNOWN":                               504,
	"SYNC_UNKNOWN":                                 505,
	"BUILD_UNKNOWN":                                506,
	"DEVINIT_UNKNOWN":                              507,
	"CLEANUP_UNKNOWN":                              508,
	"INIT_UNKNOWN":                                 510,
	"BUILD_DOCKER_UNKNOWN":                         511,
	"TEST_UNKNOWN":                                 512,
	"SYNC_INIT_ERROR":                              601,
	"DEVINIT_REGISTER_BUILD_DEPS":                  701,
	"DEVINIT_REGISTER_TEST_DEPS":                   702,
	"DEVINIT_REGISTER_DEPLOY_DEPS":                 703,
	"DEVINIT_REGISTER_CONFIG_DEP":                  704,
	"DEVINIT_UNSUPPORTED_V1_MANIFEST":              705,
	"STATUSCHECK_USER_CANCELLED":                   800,
	"STATUSCHECK_DEADLINE_EXCEEDED":                801,
	"BUILD_CANCELLED":                              802,
	"DEPLOY_CANCELLED":                             803,
	"BUILD_DOCKER_CANCELLED":                       804,
	"BUILD_DOCKER_DEADLINE":                        805,
	"INIT_CREATE_TAGGER_ERROR":                     901,
	"INIT_MINIKUBE_PAUSED_ERROR":                   902,
	"INIT_MINIKUBE_NOT_RUNNING_ERROR":              903,
	"INIT_CREATE_BUILDER_ERROR":                    904,
	"INIT_CREATE_DEPLOYER_ERROR":                   905,
	"INIT_CREATE_TEST_DEP_ERROR":                   906,
	"INIT_CACHE_ERROR":                             907,
	"INIT_CREATE_WATCH_TRIGGER_ERROR":              908,
	"INIT_CREATE_ARTIFACT_DEP_ERROR":               909,
	"DEPLOY_CLUSTER_CONNECTION_ERR":                1001,
	"DEPLOY_DEBUG_HELPER_RETRIEVE_ERR":             1002,
	"DEPLOY_CLEANUP_ERR":                           1003,
	"DEPLOY_HELM_APPLY_LABELS":                     1004,
	"DEPLOY_HELM_USER_ERR":                         1005,
	"DEPLOY_NO_MATCHING_BUILD":                     1006,
	"DEPLOY_HELM_VERSION_ERR":                      1007,
	"DEPLOY_HELM_MIN_VERSION_ERR":                  1008,
	"DEPLOY_KUBECTL_VERSION_ERR":                   1109,
	"DEPLOY_KUBECTL_OFFLINE_MODE_ERR":              1010,
	"DEPLOY_ERR_WAITING_FOR_DELETION":              1011,
	"DEPLOY_READ_MANIFEST_ERR":                     1012,
	"DEPLOY_READ_REMOTE_MANIFEST_ERR":              1013,
	"DEPLOY_LIST_MANIFEST_ERR":                     1014,
	"DEPLOY_KUBECTL_USER_ERR":                      1015,
	"DEPLOY_KUSTOMIZE_USER_ERR":                    1016,
	"DEPLOY_REPLACE_IMAGE_ERR":                     1017,
	"DEPLOY_TRANSFORM_MANIFEST_ERR":                1018,
	"DEPLOY_SET_LABEL_ERR":                         1019,
	"DEPLOY_MANIFEST_WRITE_ERR":                    1020,
	"DEPLOY_PARSE_MANIFEST_IMAGES_ERR":             1021,
	"DEPLOY_HELM_CREATE_NS_NOT_AVAILABLE":          1022,
	"TEST_USER_CONFIG_ERR":                         1101,
	"TEST_CST_USER_ERR":                            1102,
	"TEST_IMG_PULL_ERR":                            1103,
	"TEST_CUSTOM_CMD_PARSE_ERR":                    1104,
	"TEST_CUSTOM_CMD_RUN_NON_ZERO_EXIT_ERR":        1105,
	"TEST_CUSTOM_CMD_RUN_TIMEDOUT_ERR":             1106,
	"TEST_CUSTOM_CMD_RUN_CANCELLED_ERR":            1107,
	"TEST_CUSTOM_CMD_RUN_EXECUTION_ERR":            1108,
	"TEST_CUSTOM_CMD_RUN_EXITED_ERR":               1110,
	"TEST_CUSTOM_CMD_RUN_ERR":                      1111,
	"TEST_CUSTOM_DEPENDENCIES_CMD_ERR":             1112,
	"TEST_CUSTOM_DEPENDENCIES_UNMARSHALL_ERR":      1113,
	"TEST_CUSTOM_CMD_RETRIEVE_ERR":                 1114,
	"CONFIG_FILE_PARSING_ERR":                      1201,
	"CONFIG_FILE_NOT_FOUND_ERR":                    1202,
	"CONFIG_DEPENDENCY_NOT_FOUND_ERR":              1203,
	"CONFIG_DUPLICATE_NAMES_SAME_FILE_ERR":         1204,
	"CONFIG_DUPLICATE_NAMES_ACROSS_FILES_ERR":      1205,
	"CONFIG_BAD_FILTER_ERR":                        1206,
	"CONFIG_ZERO_FOUND_ERR":                        1207,
	"CONFIG_APPLY_PROFILES_ERR":                    1208,
	"CONFIG_DEFAULT_VALUES_ERR":                    1209,
	"CONFIG_FILE_PATHS_SUBSTITUTION_ERR":           1210,
	"CONFIG_MULTI_IMPORT_PROFILE_CONFLICT_ERR":     1211,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_888b6bd9597961ff, []int{6}
}

// Enum for Suggestion codes
type SuggestionCode int32

const (
	// default nil suggestion.
	// This is usually set when no error happens.
	SuggestionCode_NIL SuggestionCode = 0
	// Add Default Repo
	SuggestionCode_ADD_DEFAULT_REPO SuggestionCode = 100
	// Verify Default Repo
	SuggestionCode_CHECK_DEFAULT_REPO SuggestionCode = 101
	// Verify default repo in the global config
	SuggestionCode_CHECK_DEFAULT_REPO_GLOBAL_CONFIG SuggestionCode = 102
	// run gcloud docker auth configure
	SuggestionCode_GCLOUD_DOCKER_AUTH_CONFIGURE SuggestionCode = 103
	// Run docker auth configure
	SuggestionCode_DOCKER_AUTH_CONFIGURE SuggestionCode = 104
	// Verify Gcloud Project
	SuggestionCode_CHECK_GCLOUD_PROJECT SuggestionCode = 105
	// Check if docker is running
	SuggestionCode_CHECK_DOCKER_RUNNING SuggestionCode = 106
	// Fix User Build Error
	SuggestionCode_FIX_USER_BUILD_ERR SuggestionCode = 107
	// Docker build internal error, try again
	SuggestionCode_DOCKER_BUILD_RETRY SuggestionCode = 108
	// Fix `cacheFrom` config for given artifact and try again
	SuggestionCode_FIX_CACHE_FROM_ARTIFACT_CONFIG SuggestionCode = 109
	// Fix `dockerfile` config for a given artifact and try again.
	SuggestionCode_FIX_SKAFFOLD_CONFIG_DOCKERFILE SuggestionCode = 110
	// Use a supported Jib plugin type
	SuggestionCode_FIX_JIB_PLUGIN_CONFIGURATION SuggestionCode = 111
	// Docker build network invalid docker container name (or id).
	SuggestionCode_FIX_DOCKER_NETWORK_CONTAINER_NAME SuggestionCode = 112
	// Docker build network container not existing in the current context.
	SuggestionCode_CHECK_DOCKER_NETWORK_CONTAINER_RUNNING SuggestionCode = 113
	// Executing extractContainerNameFromNetworkMode with a non valid mode (only container mode allowed)
	SuggestionCode_FIX_DOCKER_NETWORK_MODE_WHEN_EXTRACTING_CONTAINER_NAME SuggestionCode = 114
	// Check cluster connection
	SuggestionCode_CHECK_CLUSTER_CONNECTION SuggestionCode = 201
	// Check minikube status
	SuggestionCode_CHECK_MINIKUBE_STATUS SuggestionCode = 202
	// Install helm tool
	SuggestionCode_INSTALL_HELM SuggestionCode = 203
	// Upgrade helm tool
	SuggestionCode_UPGRADE_HELM SuggestionCode = 204
	// Fix helm `releases.artifactOverrides` config to match with `build.artiofacts`
	SuggestionCode_FIX_SKAFFOLD_CONFIG_HELM_ARTIFACT_OVERRIDES SuggestionCode = 205
	// Upgrade helm version to v3.2.0 and higher.
	SuggestionCode_UPGRADE_HELM32 SuggestionCode = 206
	// Set `releases.createNamespace` to false.
	SuggestionCode_FIX_SKAFFOLD_CONFIG_HELM_CREATE_NAMESPACE SuggestionCode = 207
	// Install kubectl tool
	SuggestionCode_INSTALL_KUBECTL SuggestionCode = 220
	// Container run error
	SuggestionCode_CHECK_CONTAINER_LOGS SuggestionCode = 301
	// Pod Health check error
	SuggestionCode_CHECK_READINESS_PROBE SuggestionCode = 302
	// Check Container image
	SuggestionCode_CHECK_CONTAINER_IMAGE SuggestionCode = 303
	// Node pressure error
	SuggestionCode_ADDRESS_NODE_MEMORY_PRESSURE SuggestionCode = 400
	// Node disk pressure error
	SuggestionCode_ADDRESS_NODE_DISK_PRESSURE SuggestionCode = 401
	// Node network unavailable error
	SuggestionCode_ADDRESS_NODE_NETWORK_UNAVAILABLE SuggestionCode = 402
	// Node PID pressure error
	SuggestionCode_ADDRESS_NODE_PID_PRESSURE SuggestionCode = 403
	// Node unschedulable error
	SuggestionCode_ADDRESS_NODE_UNSCHEDULABLE SuggestionCode = 404
	// Node unreachable error
	SuggestionCode_ADDRESS_NODE_UNREACHABLE SuggestionCode = 405
	// Node not ready error
	SuggestionCode_ADDRESS_NODE_NOT_READY SuggestionCode = 406
	// Scheduler failure error
	SuggestionCode_ADDRESS_FAILED_SCHEDULING SuggestionCode = 407
	// Cluster Connectivity error
	SuggestionCode_CHECK_HOST_CONNECTION SuggestionCode = 408
	// Minikube is stopped: use `minikube start`
	SuggestionCode_START_MINIKUBE SuggestionCode = 501
	// Minikube is paused: use `minikube unpause`
	SuggestionCode_UNPAUSE_MINIKUBE SuggestionCode = 502
	// Run Docker pull for the image with v1 manifest and try again.
	SuggestionCode_RUN_DOCKER_PULL SuggestionCode = 551
	// Rerun with correct offline flag value.
	SuggestionCode_SET_RENDER_FLAG_OFFLINE_FALSE SuggestionCode = 600
	// Check configuration file path
	SuggestionCode_CONFIG_CHECK_FILE_PATH SuggestionCode = 700
	// Check dependency config definition
	SuggestionCode_CONFIG_CHECK_DEPENDENCY_DEFINITION SuggestionCode = 701
	// Change config name to avoid duplicates
	SuggestionCode_CONFIG_CHANGE_NAMES SuggestionCode = 702
	// Check config filter
	SuggestionCode_CONFIG_CHECK_FILTER SuggestionCode = 703
	// Check profile definition in current config
	SuggestionCode_CONFIG_CHECK_PROFILE_DEFINITION SuggestionCode = 704
	// Check active profile selection for dependency config
	SuggestionCode_CONFIG_CHECK_DEPENDENCY_PROFILES_SELECTION SuggestionCode = 705
	// Open an issue so this situation can be diagnosed
	SuggestionCode_OPEN_ISSUE SuggestionCode = 900
	// Test error suggestion codes
	SuggestionCode_CHECK_CUSTOM_COMMAND                    SuggestionCode = 1000
	SuggestionCode_FIX_CUSTOM_COMMAND_TIMEOUT              SuggestionCode = 1001
	SuggestionCode_CHECK_CUSTOM_COMMAND_DEPENDENCIES_CMD   SuggestionCode = 1002
	SuggestionCode_CHECK_CUSTOM_COMMAND_DEPENDENCIES_PATHS SuggestionCode = 1003
	SuggestionCode_CHECK_TEST_COMMAND_AND_IMAGE_NAME       SuggestionCode = 1004
)

var SuggestionCode_name = map[int32]string{
	0:    "NIL",
	100:  "ADD_DEFAULT_REPO",
	101:  "CHECK_DEFAULT_REPO",
	102:  "CHECK_DEFAULT_REPO_GLOBAL_CONFIG",
	103:  "GCLOUD_DOCKER_AUTH_CONFIGURE",
	104:  "DOCKER_AUTH_CONFIGURE",
	105:  "CHECK_GCLOUD_PROJECT",
	106:  "CHECK_DOCKER_RUNNING",
	107:  "FIX_USER_BUILD_ERR",
	108:  "DOCKER_BUILD_RETRY",
	109:  "FIX_CACHE_FROM_ARTIFACT_CONFIG",
	110:  "FIX_SKAFFOLD_CONFIG_DOCKERFILE",
	111:  "FIX_JIB_PLUGIN_CONFIGURATION",
	112:  "FIX_DOCKER_NETWORK_CONTAINER_NAME",
	113:  "CHECK_DOCKER_NETWORK_CONTAINER_RUNNING",
	114:  "FIX_DOCKER_NETWORK_MODE_WHEN_EXTRACTING_CONTAINER_NAME",
	201:  "CHECK_CLUSTER_CONNECTION",
	202:  "CHECK_MINIKUBE_STATUS",
	203:  "INSTALL_HELM",
	204:  "UPGRADE_HELM",
	205:  "FIX_SKAFFOLD_CONFIG_HELM_ARTIFACT_OVERRIDES",
	206:  "UPGRADE_HELM32",
	207:  "FIX_SKAFFOLD_CONFIG_HELM_CREATE_NAMESPACE",
	220:  "INSTALL_KUBECTL",
	301:  "CHECK_CONTAINER_LOGS",
	302:  "CHECK_READINESS_PROBE",
	303:  "CHECK_CONTAINER_IMAGE",
	400:  "ADDRESS_NODE_MEMORY_PRESSURE",
	401:  "ADDRESS_NODE_DISK_PRESSURE",
	402:  "ADDRESS_NODE_NETWORK_UNAVAILABLE",
	403:  "ADDRESS_NODE_PID_PRESSURE",
	404:  "ADDRESS_NODE_UNSCHEDULABLE",
	405:  "ADDRESS_NODE_UNREACHABLE",
	406:  "ADDRESS_NODE_NOT_READY",
	407:  "ADDRESS_FAILED_SCHEDULING",
	408:  "CHECK_HOST_CONNECTION",
	501:  "START_MINIKUBE",
	502:  "UNPAUSE_MINIKUBE",
	551:  "RUN_DOCKER_PULL",
	600:  "SET_RENDER_FLAG_OFFLINE_FALSE",
	700:  "CONFIG_CHECK_FILE_PATH",
	701:  "CONFIG_CHECK_DEPENDENCY_DEFINITION",
	702:  "CONFIG_CHANGE_NAMES",
	703:  "CONFIG_CHECK_FILTER",
	704:  "CONFIG_CHECK_PROFILE_DEFINITION",
	705:  "CONFIG_CHECK_DEPENDENCY_PROFILES_SELECTION",
	900:  "OPEN_ISSUE",
	1000: "CHECK_CUSTOM_COMMAND",
	1001: "FIX_CUSTOM_COMMAND_TIMEOUT",
	1002: "CHECK_CUSTOM_COMMAND_DEPENDENCIES_CMD",
	1003: "CHECK_CUSTOM_COMMAND_DEPENDENCIES_PATHS",
	1004: "CHECK_TEST_COMMAND_AND_IMAGE_NAME",
}

var SuggestionCode_value = map[string]int32{
	"NIL":                                                    0,
	"ADD_DEFAULT_REPO":                                       100,
	"CHECK_DEFAULT_REPO":                                     101,
	"CHECK_DEFAULT_REPO_GLOBAL_CONFIG":                       102,
	"GCLOUD_DOCKER_AUTH_CONFIGURE":                           103,
	"DOCKER_AUTH_CONFIGURE":                                  104,
	"CHECK_GCLOUD_PROJECT":                                   105,
	"CHECK_DOCKER_RUNNING":                                   106,
	"FIX_USER_BUILD_ERR":                                     107,
	"DOCKER_BUILD_RETRY":                                     108,
	"FIX_CACHE_FROM_ARTIFACT_CONFIG":                         109,
	"FIX_SKAFFOLD_CONFIG_DOCKERFILE":                         110,
	"FIX_JIB_PLUGIN_CONFIGURATION":                           111,
	"FIX_DOCKER_NETWORK_CONTAINER_NAME":                      112,
	"CHECK_DOCKER_NETWORK_CONTAINER_RUNNING":                 113,
	"FIX_DOCKER_NETWORK_MODE_WHEN_EXTRACTING_CONTAINER_NAME": 114,
	"CHECK_CLUSTER_CONNECTION":                               201,
	"CHECK_MINIKUBE_STATUS":                                  202,
	"INSTALL_HELM":                                           203,
	"UPGRADE_HELM":                                           204,
	"FIX_SKAFFOLD_CONFIG_HELM_ARTIFACT_OVERRIDES":            205,
	"UPGRADE_HELM32":                                         206,
	"FIX_SKAFFOLD_CONFIG_HELM_CREATE_NAMESPACE":              207,
	"INSTALL_KUBECTL":                                        220,
	"CHECK_CONTAINER_LOGS":                                   301,
	"CHECK_READINESS_PROBE":                                  302,
	"CHECK_CONTAINER_IMAGE":                                  303,
	"ADDRESS_NODE_MEMORY_PRESSURE":                           400,
	"ADDRESS_NODE_DISK_PRESSURE":                             401,
	"ADDRESS_NODE_NETWORK_UNAVAILABLE":                       402,
	"ADDRESS_NODE_PID_PRESSURE":                              403,
	"ADDRESS_NODE_UNSCHEDULABLE":                             404,
	"ADDRESS_NODE_UNREACHABLE":                               405,
	"ADDRESS_NODE_NOT_READY":                                 406,
	"ADDRESS_FAILED_SCHEDULING":                              407,
	"CHECK_HOST_CONNECTION":                                  408,
	"START_MINIKUBE":                                         501,
	"UNPAUSE_MINIKUBE":                                       502,
	"RUN_DOCKER_PULL":                                        551,
	"SET_RENDER_FLAG_OFFLINE_FALSE":                          600,
	"CONFIG_CHECK_FILE_PATH":                                 700,
	"CONFIG_CHECK_DEPENDENCY_DEFINITION":                     701,
	"CONFIG_CHANGE_NAMES":                                    702,
	"CONFIG_CHECK_FILTER":                                    703,
	"CONFIG_CHECK_PROFILE_DEFINITION":                        704,
	"CONFIG_CHECK_DEPENDENCY_PROFILES_SELECTION":             705,
	"OPEN_ISSUE":                                             900,
	"CHECK_CUSTOM_COMMAND":                                   1000,
	"FIX_CUSTOM_COMMAND_TIMEOUT":                             1001,
	"CHECK_CUSTOM_COMMAND_DEPENDENCIES_CMD":                  1002,
	"CHECK_CUSTOM_COMMAND_DEPENDENCIES_PATHS":                1003,
	"CHECK_TEST_COMMAND_AND_IMAGE_NAME":                      1004,
}

func (x SuggestionCode) String() string {
	return proto.EnumName(SuggestionCode_name, int32(x))
}

func (SuggestionCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_888b6bd9597961ff, []int{7}
}

func init() {
	proto.RegisterEnum("proto.enums.BuilderType", BuilderType_name, BuilderType_value)
	proto.RegisterEnum("proto.enums.BuildType", BuildType_name, BuildType_value)
	proto.RegisterEnum("proto.enums.TesterType", TesterType_name, TesterType_value)
	proto.RegisterEnum("proto.enums.DeployerType", DeployerType_name, DeployerType_value)
	proto.RegisterEnum("proto.enums.ClusterType", ClusterType_name, ClusterType_value)
	proto.RegisterEnum("proto.enums.LogLevel", LogLevel_name, LogLevel_value)
	proto.RegisterEnum("proto.enums.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterEnum("proto.enums.SuggestionCode", SuggestionCode_name, SuggestionCode_value)
}

func init() { proto.RegisterFile("enums.proto", fileDescriptor_888b6bd9597961ff) }

var fileDescriptor_888b6bd9597961ff = []byte{
	// 2724 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x59, 0x59, 0x90, 0x1c, 0xc5,
	0x11, 0x65, 0x77, 0x76, 0x77, 0x66, 0x4b, 0x02, 0x8a, 0x42, 0x12, 0xab, 0xfb, 0x00, 0x09, 0x58,
	0xb0, 0x84, 0x8d, 0x83, 0x0f, 0xff, 0xd5, 0x74, 0xe7, 0xcc, 0x94, 0xa6, 0xbb, 0xba, 0xa3, 0xaa,
	0x7a, 0x57, 0xab, 0x9f, 0x0e, 0xb0, 0x46, 0x8b, 0x60, 0xa5, 0x11, 0xda, 0x5d, 0x6c, 0x7c, 0x85,
	0x3f, 0x7c, 0x1f, 0x11, 0xbe, 0x6f, 0x47, 0xf8, 0x0c, 0xff, 0x18, 0x30, 0xbe, 0x4f, 0x0c, 0xe1,
	0x1f, 0x63, 0x0c, 0xf8, 0x36, 0x38, 0xfc, 0x69, 0x47, 0xf8, 0xc0, 0x47, 0x60, 0x10, 0x37, 0x76,
	0x64, 0x55, 0x5f, 0x73, 0x2c, 0xfe, 0x20, 0x18, 0x55, 0xbe, 0xca, 0xca, 0xcc, 0xca, 0xca, 0x7c,
	0xd9, 0x4b, 0x36, 0xf5, 0xce, 0xac, 0x9f, 0x5e, 0x3d, 0x7c, 0xf6, 0x5c, 0x7f, 0xad, 0xcf, 0x36,
	0xd9, 0xff, 0x1d, 0xb6, 0x4b, 0xf3, 0x7d, 0xb2, 0xa9, 0xb9, 0x7e, 0x6a, 0xe5, 0x44, 0xef, 0x9c,
	0xb9, 0xe3, 0x6c, 0x8f, 0xcd, 0x91, 0x2d, 0x89, 0xec, 0xca, 0x68, 0x51, 0xa6, 0xcd, 0x44, 0x04,
	0x3e, 0xa8, 0xd4, 0x2c, 0xc5, 0x40, 0x2f, 0x60, 0x75, 0x52, 0x3b, 0x2a, 0x9a, 0x74, 0x82, 0xcd,
	0x92, 0xe9, 0x26, 0x3f, 0x0e, 0x01, 0x9d, 0x64, 0x17, 0x11, 0x62, 0x51, 0x31, 0xf7, 0xba, 0x9a,
	0xd6, 0x18, 0x21, 0x33, 0x5e, 0xa2, 0x4d, 0x14, 0xd2, 0x29, 0xfc, 0xdd, 0xe5, 0x52, 0x74, 0x23,
	0x3a, 0x8d, 0xbf, 0xfd, 0xc8, 0xeb, 0x82, 0xa2, 0x33, 0xf3, 0x3e, 0x99, 0xb5, 0x07, 0xda, 0xe3,
	0xb6, 0x11, 0x36, 0x70, 0x5c, 0x7e, 0xd8, 0x26, 0x52, 0xf7, 0x82, 0x44, 0x1b, 0x50, 0x74, 0x02,
	0x4f, 0x6e, 0x7b, 0x4d, 0x3a, 0x89, 0x27, 0x07, 0x91, 0xc7, 0x03, 0x5a, 0x9b, 0xef, 0x12, 0x62,
	0x7a, 0xab, 0x6b, 0x99, 0xd5, 0x5b, 0xc9, 0x25, 0xb9, 0x1a, 0x03, 0xda, 0xe4, 0x5a, 0x1a, 0x64,
	0x2a, 0x91, 0xc2, 0xd0, 0x09, 0xb6, 0x8b, 0xcc, 0x79, 0x91, 0x34, 0x5c, 0x48, 0x50, 0xa9, 0x36,
	0x2a, 0xf1, 0x4c, 0xa2, 0xc0, 0x82, 0xe9, 0xe4, 0x7c, 0x44, 0x36, 0xfb, 0xbd, 0xb3, 0x2b, 0xfd,
	0x3b, 0x32, 0x75, 0xdb, 0xc9, 0xd6, 0x5c, 0x9d, 0x0f, 0x71, 0x10, 0x2d, 0x95, 0x51, 0x68, 0x90,
	0xa9, 0x0e, 0x04, 0x21, 0x9d, 0x60, 0x17, 0x92, 0xd9, 0xae, 0xf5, 0x55, 0x1c, 0x07, 0x3a, 0x89,
	0x16, 0x77, 0x93, 0x26, 0x78, 0x06, 0xad, 0x13, 0x64, 0x93, 0xb7, 0xb2, 0x5e, 0x98, 0x57, 0x09,
	0x6a, 0xe6, 0x55, 0xae, 0x6e, 0x33, 0x69, 0x84, 0x42, 0x0a, 0xdc, 0x99, 0x39, 0xda, 0x05, 0xe7,
	0x68, 0x64, 0x3a, 0xa0, 0x68, 0x6d, 0xfe, 0x28, 0x69, 0x04, 0xfd, 0xe5, 0xa0, 0x77, 0x7b, 0x6f,
	0x05, 0x97, 0x7d, 0x68, 0x26, 0x6d, 0x67, 0x87, 0x90, 0xad, 0x88, 0x4e, 0xe0, 0xaf, 0x45, 0xae,
	0xa4, 0xdb, 0x05, 0x4a, 0x45, 0x8a, 0xd6, 0xf0, 0x67, 0x8b, 0x1b, 0x1e, 0xd0, 0x29, 0xfc, 0x19,
	0x73, 0x29, 0x3c, 0x3a, 0x3d, 0x7f, 0xef, 0x01, 0x42, 0xf4, 0xda, 0x8d, 0x6b, 0xeb, 0xab, 0x5e,
	0xff, 0x44, 0x8f, 0xcd, 0x90, 0xc9, 0xa8, 0x4b, 0x2f, 0x60, 0x73, 0xe4, 0x52, 0x6d, 0xb8, 0x49,
	0xb4, 0xd7, 0x01, 0xaf, 0x9b, 0xea, 0xc4, 0xf3, 0x40, 0x6b, 0xfa, 0xd3, 0x09, 0xc6, 0xc8, 0x85,
	0xee, 0x5a, 0xf2, 0xb5, 0x07, 0x26, 0xd8, 0xa5, 0xe4, 0x22, 0x17, 0x94, 0x62, 0xf1, 0x67, 0x13,
	0xec, 0x12, 0xb2, 0xd9, 0x06, 0x3e, 0x5f, 0x7a, 0xd0, 0x86, 0xdc, 0xed, 0x8d, 0x13, 0xdd, 0x49,
	0xb9, 0x5d, 0x4f, 0x7d, 0x90, 0x02, 0x7c, 0xda, 0x63, 0x3b, 0xc9, 0x65, 0x99, 0x54, 0x45, 0x47,
	0xc1, 0x33, 0xa9, 0x8c, 0x4c, 0xda, 0x8a, 0x12, 0xe9, 0xd3, 0x93, 0xec, 0x72, 0xb2, 0xd7, 0x09,
	0x5d, 0xd2, 0xa4, 0x3e, 0x87, 0x30, 0x92, 0x16, 0xa2, 0x12, 0x29, 0x85, 0x6c, 0xd3, 0x65, 0xb6,
	0x85, 0x50, 0x07, 0x4a, 0x34, 0xa8, 0xd4, 0x39, 0x7e, 0x73, 0x79, 0x6a, 0xb6, 0x35, 0x91, 0x7c,
	0x81, 0x8b, 0x80, 0x37, 0x03, 0xa0, 0xa7, 0xd8, 0x6e, 0xb2, 0x7d, 0x58, 0x9a, 0x98, 0x4e, 0xa4,
	0xc4, 0x71, 0xf0, 0xe9, 0x2d, 0xa5, 0x51, 0x99, 0x58, 0x2f, 0x69, 0x03, 0x21, 0xea, 0xa6, 0xb7,
	0xb2, 0xfd, 0x64, 0xf7, 0x80, 0x10, 0xad, 0x09, 0x23, 0x5f, 0xb4, 0x04, 0xf8, 0x16, 0xb2, 0xc2,
	0xae, 0x20, 0xfb, 0x46, 0x20, 0x22, 0x8c, 0x03, 0x08, 0x41, 0x9a, 0x0c, 0x75, 0x9a, 0xed, 0x21,
	0x3b, 0x86, 0xbc, 0x33, 0x3c, 0x0d, 0x22, 0xad, 0xad, 0xfc, 0xcc, 0x88, 0xbc, 0x15, 0xa9, 0xa6,
	0xf0, 0x7d, 0x90, 0x56, 0xde, 0x1f, 0x71, 0xc2, 0x8b, 0x64, 0x2b, 0x10, 0x9e, 0xb1, 0xe2, 0xb3,
	0x6c, 0x1f, 0xd9, 0x35, 0x20, 0xb6, 0x91, 0xa9, 0x84, 0xf7, 0x36, 0x76, 0x80, 0xec, 0x19, 0x40,
	0x08, 0xb9, 0xc0, 0x03, 0xe1, 0xa7, 0x31, 0x57, 0xdc, 0x79, 0x7b, 0x6e, 0xd8, 0x88, 0x96, 0x08,
	0xa0, 0xa2, 0x63, 0x75, 0xc4, 0x55, 0x8f, 0x7b, 0x1d, 0x48, 0x5b, 0x2a, 0x0a, 0xd3, 0x38, 0x09,
	0x02, 0xab, 0x65, 0x8d, 0xed, 0x25, 0x3b, 0x07, 0x50, 0x6d, 0x30, 0xa9, 0x2f, 0xda, 0x98, 0x29,
	0x08, 0x58, 0x2f, 0x83, 0xaa, 0xa0, 0x2d, 0xb4, 0x51, 0x4b, 0xc3, 0x90, 0xdb, 0x4b, 0x48, 0xfe,
	0x84, 0x8e, 0x8a, 0x66, 0x1a, 0x07, 0x49, 0x5b, 0x48, 0xf7, 0x8a, 0x5e, 0x57, 0x5e, 0x3a, 0x8a,
	0xda, 0x8a, 0xfb, 0x01, 0xe0, 0xc3, 0xb5, 0x0a, 0x5e, 0x5f, 0xde, 0x2a, 0x4a, 0x43, 0xbe, 0x00,
	0xb2, 0x10, 0xde, 0xc1, 0xe6, 0xc9, 0x21, 0x21, 0x85, 0x29, 0x6e, 0x0c, 0xcc, 0x62, 0xa4, 0xba,
	0x69, 0x20, 0xb4, 0x11, 0xb2, 0x9d, 0x16, 0x45, 0x43, 0xd3, 0x37, 0xb0, 0xc3, 0x64, 0x7e, 0x1c,
	0x36, 0x0f, 0x5f, 0x59, 0x60, 0x24, 0x0f, 0x81, 0xbe, 0x91, 0x5d, 0x47, 0xae, 0x1d, 0x87, 0x2f,
	0x71, 0x7e, 0x04, 0xda, 0x46, 0x15, 0x8e, 0x09, 0x6d, 0xe8, 0x9b, 0x30, 0xaa, 0x2f, 0x77, 0x42,
	0x18, 0xf9, 0x40, 0xdf, 0x8c, 0x11, 0x19, 0x87, 0x8a, 0xb9, 0xd2, 0x60, 0xdd, 0x7a, 0x0b, 0xdb,
	0x4b, 0x76, 0x54, 0x9f, 0xb4, 0x08, 0x79, 0x1b, 0xca, 0x8b, 0xf9, 0xea, 0x24, 0xbb, 0x9c, 0xec,
	0xa9, 0x02, 0x4a, 0x9b, 0x3c, 0x05, 0x1c, 0x5d, 0xa7, 0x77, 0x4e, 0xb2, 0x03, 0x64, 0x77, 0x15,
	0xa4, 0x12, 0x59, 0x01, 0xa2, 0xa2, 0xbb, 0x26, 0xd9, 0x41, 0xb2, 0x6f, 0xbc, 0x22, 0x03, 0x2a,
	0x14, 0x92, 0x1b, 0xf0, 0xe9, 0xdd, 0x93, 0xec, 0x1a, 0x72, 0xa8, 0x0a, 0x73, 0x15, 0x04, 0x9f,
	0x45, 0xaa, 0xa2, 0x20, 0x88, 0x12, 0x93, 0xc6, 0x20, 0x7d, 0x3c, 0xf7, 0x6b, 0x93, 0xec, 0x5a,
	0x72, 0xe5, 0x40, 0x41, 0x32, 0xdc, 0x40, 0x2b, 0x09, 0x34, 0x8c, 0xa2, 0xef, 0x79, 0x19, 0x0b,
	0x14, 0x68, 0xc3, 0x95, 0x75, 0xe6, 0x4f, 0x93, 0x6c, 0x07, 0xd9, 0x5a, 0x85, 0x25, 0xb2, 0x03,
	0x3c, 0x30, 0x9d, 0x25, 0xfa, 0xe7, 0x11, 0x15, 0x32, 0xf2, 0x21, 0x0d, 0x21, 0x8c, 0xd4, 0x52,
	0x1a, 0x2b, 0xd0, 0x3a, 0x51, 0x40, 0x3f, 0x50, 0x1b, 0x0e, 0x9a, 0x85, 0xf9, 0x42, 0x77, 0x4b,
	0xd0, 0x07, 0x6b, 0xec, 0x6a, 0x72, 0xc5, 0x08, 0x28, 0xbf, 0xa2, 0x6a, 0x35, 0xfa, 0x50, 0x6d,
	0x38, 0xbe, 0x16, 0x1a, 0xe3, 0x43, 0xcc, 0xd5, 0x7d, 0x78, 0xfc, 0x99, 0x89, 0xc4, 0x7f, 0xf9,
	0x89, 0x53, 0xf4, 0x91, 0x1a, 0xdb, 0x4f, 0x76, 0x8d, 0x01, 0x29, 0xe0, 0x5e, 0xc7, 0x42, 0x3e,
	0x5a, 0x1b, 0xce, 0x08, 0x67, 0x16, 0x16, 0x54, 0xe0, 0xfe, 0x12, 0xfd, 0xd8, 0x88, 0x31, 0x2d,
	0x2e, 0x02, 0xf0, 0xd3, 0xec, 0x20, 0x8c, 0xe1, 0xc7, 0x6b, 0xec, 0x4a, 0x72, 0xa0, 0x8a, 0xc9,
	0x1a, 0x1e, 0x86, 0x5c, 0x82, 0x67, 0x44, 0xe4, 0x4a, 0xd4, 0x27, 0x47, 0xac, 0xce, 0x81, 0xe8,
	0x5c, 0x57, 0x04, 0x01, 0xf8, 0xf4, 0x53, 0x23, 0x91, 0x2a, 0xb4, 0x05, 0x02, 0xf3, 0xa2, 0x05,
	0xc6, 0xeb, 0x58, 0x7d, 0x9f, 0xae, 0x0d, 0x5f, 0x50, 0x25, 0x7d, 0x4a, 0xd8, 0x67, 0x6a, 0xec,
	0x10, 0xd9, 0xbf, 0x51, 0xe2, 0x94, 0xb8, 0xcf, 0x8e, 0xc4, 0x2b, 0x8e, 0xfc, 0x14, 0x5f, 0x94,
	0xe0, 0x81, 0x38, 0x8e, 0xae, 0xfe, 0xa4, 0x86, 0xad, 0x2f, 0x2f, 0x38, 0xae, 0xb7, 0x3c, 0x59,
	0x1b, 0x6e, 0x94, 0x99, 0x9c, 0x3e, 0x35, 0x72, 0x70, 0xbe, 0x73, 0xf0, 0xa2, 0xce, 0xd7, 0xd8,
	0x3c, 0x39, 0x38, 0x3e, 0x57, 0x17, 0xb9, 0xb0, 0x05, 0x27, 0xd7, 0xf9, 0x74, 0x8d, 0xed, 0x21,
	0xdb, 0xc7, 0xe9, 0x84, 0x05, 0x90, 0x86, 0xbe, 0x58, 0xab, 0x34, 0xe2, 0x7c, 0xd3, 0x33, 0x35,
	0x6c, 0xc4, 0x7a, 0x49, 0x7a, 0xc5, 0xd2, 0xb3, 0xb5, 0xb2, 0x89, 0xe7, 0x6b, 0xcf, 0xd5, 0xd8,
	0x16, 0x72, 0xb1, 0x0f, 0x0b, 0xb6, 0x8a, 0xe4, 0xab, 0xcf, 0xdb, 0x55, 0x2f, 0x00, 0x2e, 0x93,
	0xb8, 0x58, 0x7d, 0xc1, 0xaa, 0x1c, 0x00, 0xbe, 0x54, 0x63, 0xdb, 0xc9, 0x96, 0xa1, 0x3e, 0xea,
	0x44, 0xff, 0xad, 0x15, 0x4c, 0x20, 0x5f, 0x7a, 0xeb, 0x14, 0xaa, 0xb5, 0x36, 0x59, 0x2d, 0x2e,
	0x98, 0x8f, 0x4d, 0xb1, 0x7d, 0x64, 0x67, 0x6e, 0x82, 0x2b, 0xfe, 0xa0, 0x32, 0x0e, 0xe8, 0x43,
	0xac, 0xe9, 0x8f, 0xa6, 0x31, 0x65, 0x47, 0x10, 0x56, 0xb7, 0x05, 0xdc, 0x3b, 0x8d, 0xd7, 0x38,
	0x02, 0xc8, 0x42, 0x62, 0x21, 0x3f, 0x9e, 0x1e, 0x7b, 0x0a, 0x36, 0x4c, 0xd1, 0x46, 0x08, 0xbd,
	0x6f, 0x9a, 0x5d, 0x41, 0xf6, 0x96, 0xa1, 0xd0, 0x49, 0x1c, 0x47, 0x0a, 0x7b, 0xf5, 0xc2, 0x2b,
	0xd3, 0x90, 0x4b, 0xd1, 0x42, 0x86, 0x78, 0xff, 0xf4, 0xf0, 0xf3, 0xb1, 0x9c, 0xc3, 0xe3, 0xd2,
	0x03, 0x9b, 0xcc, 0x9f, 0x9b, 0x19, 0x7e, 0x3e, 0x3e, 0x70, 0x3f, 0x10, 0x12, 0x52, 0x38, 0xe6,
	0x01, 0xf8, 0xe0, 0xd3, 0xcf, 0xcf, 0x60, 0x20, 0x9c, 0x87, 0xe5, 0xce, 0x2f, 0xcc, 0xb0, 0xad,
	0x84, 0x66, 0x46, 0x97, 0xcb, 0x5f, 0x9c, 0x61, 0x3b, 0xc9, 0xb6, 0xa1, 0x0e, 0x9b, 0x0b, 0xbf,
	0x34, 0x83, 0xc5, 0x6c, 0x90, 0x43, 0x64, 0xc7, 0xd1, 0x2f, 0xcf, 0xb0, 0xdd, 0x64, 0xce, 0x7a,
	0x63, 0x2b, 0x39, 0xa4, 0x86, 0xb7, 0xdb, 0x05, 0x41, 0x7a, 0x7b, 0x1d, 0x3d, 0xb1, 0xe2, 0x9c,
	0x77, 0xa6, 0x31, 0x4f, 0xb4, 0x23, 0x27, 0x91, 0xa2, 0xef, 0xa8, 0x63, 0x40, 0x06, 0x01, 0x15,
	0xde, 0x95, 0xa1, 0xde, 0x59, 0xc7, 0xec, 0xac, 0x9e, 0x92, 0x0f, 0x0b, 0x4e, 0xfe, 0xae, 0xf2,
	0x98, 0x4c, 0x5e, 0xf0, 0x68, 0x07, 0x78, 0xf7, 0x08, 0x20, 0xbf, 0xd8, 0x0c, 0xf0, 0x9e, 0x3a,
	0xc6, 0xc5, 0x01, 0x2c, 0xb5, 0x70, 0xcb, 0xef, 0x2d, 0xcd, 0xcb, 0xf6, 0x2d, 0x72, 0x7c, 0xd7,
	0x46, 0x89, 0x8a, 0x97, 0xef, 0xab, 0x63, 0x01, 0xaa, 0xa2, 0xb0, 0x0d, 0xb4, 0xb8, 0x57, 0x3d,
	0xe1, 0xfd, 0x75, 0xbc, 0xb3, 0x3c, 0xf2, 0x19, 0x2d, 0x1f, 0xaa, 0x64, 0x7f, 0xad, 0x63, 0xe5,
	0x29, 0x52, 0xaa, 0x99, 0xb4, 0xd3, 0x0e, 0x04, 0xb1, 0xed, 0x2d, 0x46, 0x09, 0x58, 0x70, 0xfd,
	0xf6, 0x6f, 0x75, 0x76, 0x19, 0x61, 0x85, 0x2a, 0xf7, 0x82, 0x50, 0xf0, 0xf7, 0x3a, 0xde, 0x46,
	0x26, 0xc0, 0xb9, 0x21, 0xe5, 0x71, 0x1c, 0x2c, 0xa5, 0x01, 0x6f, 0x42, 0xa0, 0xe9, 0xe3, 0x75,
	0x7c, 0x49, 0x55, 0x71, 0xce, 0x65, 0xe9, 0x3f, 0xaa, 0x3b, 0x65, 0x94, 0x86, 0xe8, 0x26, 0x5e,
	0x80, 0x0d, 0x34, 0xfd, 0x67, 0x9d, 0xed, 0x22, 0x97, 0x55, 0x77, 0x2e, 0x80, 0xd2, 0xb9, 0xd9,
	0xff, 0xaa, 0xbb, 0xbc, 0x2f, 0xa5, 0xa1, 0x90, 0x03, 0x88, 0x7f, 0xd7, 0xdd, 0xeb, 0xb2, 0x88,
	0xbc, 0xf0, 0x56, 0x01, 0xbf, 0x6d, 0xb8, 0x87, 0x31, 0x00, 0x88, 0x5a, 0x2d, 0x9b, 0xd3, 0xc8,
	0x43, 0x2c, 0xea, 0x89, 0x7a, 0x05, 0x05, 0xaa, 0x2c, 0x63, 0xad, 0x08, 0x73, 0x32, 0x00, 0x8c,
	0x24, 0xfd, 0x4f, 0xd5, 0x17, 0xec, 0x37, 0xc5, 0xcb, 0xb2, 0x4a, 0x9e, 0xac, 0x2a, 0xb1, 0x62,
	0x05, 0x61, 0x64, 0x60, 0x10, 0xf5, 0x54, 0x55, 0x09, 0xd2, 0xb3, 0x41, 0xf1, 0xf9, 0x6a, 0x40,
	0x72, 0x7b, 0x8b, 0x68, 0x3e, 0x6d, 0xf3, 0xb5, 0x90, 0x66, 0x53, 0x5b, 0x29, 0x7f, 0x66, 0xd0,
	0xc2, 0x38, 0xe0, 0x1e, 0x64, 0xa4, 0x09, 0xc5, 0xcf, 0x56, 0x53, 0xc5, 0x28, 0x2e, 0x75, 0x2b,
	0x52, 0xe1, 0xa0, 0x01, 0xcf, 0x55, 0xef, 0x12, 0x1b, 0x8e, 0xbd, 0x63, 0x2b, 0x7a, 0xbe, 0x7a,
	0x7a, 0xb1, 0x69, 0x51, 0x09, 0xe3, 0xd4, 0xbf, 0x50, 0xcd, 0x32, 0xc7, 0xe2, 0x0a, 0x94, 0x35,
	0xc2, 0x4d, 0x06, 0x2f, 0xd6, 0xd9, 0x55, 0xe4, 0xf2, 0xea, 0xad, 0x66, 0xc9, 0x2d, 0x1d, 0x89,
	0x2c, 0xa9, 0xc5, 0x4b, 0xd6, 0x16, 0x57, 0x86, 0x75, 0x59, 0xf0, 0x50, 0xc9, 0x43, 0x0d, 0xb6,
	0x8d, 0x5c, 0x62, 0x45, 0x5e, 0x2e, 0xc6, 0xf5, 0x87, 0xcb, 0x75, 0x11, 0xb6, 0x4b, 0xaa, 0xf8,
	0x48, 0x03, 0x6d, 0x77, 0x78, 0x1b, 0xb7, 0xd4, 0x0b, 0xfd, 0x0a, 0xd5, 0xfc, 0x45, 0x03, 0x7b,
	0xda, 0xb0, 0x1c, 0x99, 0xa2, 0x8c, 0x64, 0x7a, 0x1c, 0x54, 0x84, 0xe4, 0xd6, 0x85, 0xe8, 0x97,
	0x0d, 0xf4, 0x73, 0x1c, 0xd6, 0x88, 0x10, 0x7c, 0xa4, 0x75, 0x08, 0xfb, 0x55, 0x03, 0xdb, 0xe9,
	0x38, 0x58, 0x51, 0x02, 0x2d, 0xee, 0xd7, 0x1b, 0xe2, 0xe0, 0x18, 0x78, 0x49, 0xf1, 0x88, 0x7f,
	0xd3, 0xc0, 0x6a, 0x30, 0x1e, 0x27, 0xf2, 0xb1, 0xec, 0x77, 0x0d, 0xcc, 0x9f, 0xb1, 0x20, 0xa5,
	0xe8, 0xef, 0x47, 0x2c, 0xf7, 0x01, 0x19, 0x28, 0x48, 0x4f, 0x80, 0xb6, 0x50, 0x84, 0x3d, 0xda,
	0x40, 0xea, 0xba, 0x21, 0x2c, 0x91, 0x21, 0x57, 0xba, 0xc3, 0xb3, 0xd0, 0x3e, 0xd6, 0xc0, 0x06,
	0x36, 0x72, 0x64, 0xb5, 0xb0, 0xfc, 0xc1, 0x5a, 0x95, 0x5d, 0x9f, 0x9d, 0xc1, 0x30, 0xf2, 0x59,
	0x1d, 0xa6, 0xf7, 0xcc, 0xe2, 0xdd, 0x54, 0xa5, 0xc5, 0x84, 0x66, 0xe5, 0x5f, 0x9f, 0xc5, 0x87,
	0x55, 0x76, 0x3b, 0x67, 0xc9, 0xd2, 0x10, 0xea, 0x1b, 0xb3, 0x48, 0xc4, 0x72, 0x54, 0x12, 0x07,
	0xc2, 0xb3, 0x49, 0xc5, 0x43, 0xd0, 0xa9, 0xe6, 0x21, 0x38, 0xd5, 0x08, 0xfd, 0xe6, 0x2c, 0xfa,
	0xb7, 0x01, 0x94, 0x7b, 0x0a, 0x67, 0x58, 0x04, 0xbb, 0x7c, 0xfd, 0xd6, 0x2c, 0xb6, 0xa9, 0x0c,
	0xdd, 0xe4, 0x3e, 0x8a, 0x4c, 0x96, 0x6e, 0xdf, 0xae, 0xca, 0x6c, 0x96, 0x94, 0x06, 0x7d, 0xa7,
	0xea, 0x96, 0xab, 0x97, 0xb1, 0x8a, 0x4a, 0xbd, 0xdf, 0xad, 0xca, 0x7d, 0x68, 0xf1, 0x24, 0x30,
	0xe9, 0x02, 0x0f, 0x92, 0x4c, 0xfe, 0xbd, 0x59, 0xe4, 0xa9, 0x83, 0x41, 0x33, 0x1d, 0x9d, 0xea,
	0xa4, 0xa9, 0x8d, 0x30, 0x65, 0x62, 0x7c, 0x7f, 0x96, 0xbd, 0x82, 0x5c, 0x95, 0x01, 0xc3, 0x24,
	0x30, 0x02, 0xa7, 0xf5, 0x48, 0x99, 0xfc, 0xbc, 0xc1, 0xd1, 0xfa, 0x07, 0xb3, 0xf3, 0x4f, 0x6c,
	0x26, 0x17, 0xe9, 0xf5, 0xe5, 0xe5, 0xde, 0xea, 0xda, 0xa9, 0xfe, 0x19, 0xfb, 0x11, 0xa5, 0x4e,
	0x6a, 0x52, 0x04, 0xf4, 0x02, 0xb6, 0x85, 0x50, 0xee, 0xfb, 0x85, 0x41, 0x0a, 0xe2, 0x88, 0x9e,
	0x60, 0xdb, 0x08, 0xcb, 0x09, 0x41, 0x65, 0xbd, 0x87, 0x93, 0xde, 0xe8, 0x7a, 0xda, 0x0e, 0xa2,
	0x26, 0x0f, 0xb2, 0xf7, 0x4a, 0x4f, 0xe2, 0x2c, 0xdf, 0xf6, 0x82, 0x28, 0x29, 0xfa, 0x3c, 0x4f,
	0x4c, 0x27, 0x13, 0xe3, 0x7c, 0xb0, 0xcc, 0xb6, 0x93, 0xad, 0xe3, 0x45, 0x37, 0xb3, 0x39, 0xb2,
	0xc5, 0x1d, 0x91, 0xa9, 0xc8, 0xbe, 0xb4, 0xd0, 0x53, 0xa5, 0x24, 0xdb, 0x9a, 0x7f, 0x54, 0xb9,
	0x05, 0xcd, 0x6d, 0x89, 0x63, 0xae, 0x2c, 0x38, 0x82, 0xe1, 0x3e, 0x7e, 0x6c, 0x23, 0x2c, 0xc3,
	0xe6, 0xe3, 0xba, 0x51, 0x4b, 0x74, 0x85, 0x1d, 0x20, 0x7b, 0x10, 0x5f, 0x99, 0xfe, 0x8b, 0x4e,
	0x9b, 0x39, 0x71, 0x3a, 0xc7, 0xe8, 0x2e, 0x6f, 0xb5, 0xa2, 0xc0, 0x2f, 0xe8, 0x57, 0xf1, 0x61,
	0x81, 0x9e, 0x41, 0x47, 0x11, 0x53, 0x19, 0xed, 0x73, 0x4f, 0xb8, 0x6d, 0x21, 0x7d, 0x76, 0x90,
	0xec, 0x47, 0xc4, 0x86, 0xb3, 0xb4, 0x9d, 0xb9, 0xcf, 0xe2, 0x3c, 0x3f, 0xe0, 0xda, 0x28, 0x30,
	0x77, 0xf6, 0x36, 0xf6, 0x1a, 0x72, 0xc3, 0x18, 0x95, 0xb6, 0xb9, 0x2d, 0x76, 0x00, 0xcb, 0x83,
	0x51, 0xdc, 0x1b, 0xfc, 0x0e, 0xe0, 0xce, 0x39, 0x87, 0xed, 0x22, 0xa3, 0xf0, 0x23, 0xcc, 0x81,
	0x3e, 0x30, 0x61, 0x93, 0xdb, 0x8a, 0x0b, 0x12, 0xe5, 0xc8, 0x61, 0xf6, 0xad, 0x4c, 0x48, 0x6d,
	0xb0, 0x0c, 0xd8, 0x4f, 0x89, 0x0f, 0xda, 0xa5, 0x24, 0x6e, 0x2b, 0xee, 0x83, 0x5b, 0xfa, 0xf9,
	0x04, 0xbb, 0x8e, 0x5c, 0x33, 0x2e, 0x6a, 0x8e, 0x44, 0xe4, 0x31, 0x8e, 0x16, 0x40, 0x29, 0xe1,
	0x83, 0xa6, 0x0f, 0xd9, 0x0f, 0x73, 0x55, 0x25, 0xd7, 0xbf, 0x8a, 0x3e, 0x3c, 0xc1, 0x0e, 0x93,
	0xab, 0x37, 0x54, 0x93, 0xb7, 0x0f, 0x7c, 0xbe, 0x31, 0xf7, 0x80, 0x3e, 0x32, 0x81, 0x14, 0x35,
	0x37, 0x2e, 0xff, 0x9c, 0xf9, 0xc7, 0x09, 0xec, 0x26, 0xc3, 0x03, 0x4b, 0x10, 0xb5, 0x35, 0xbd,
	0x73, 0xb2, 0xf4, 0x14, 0x3b, 0xb7, 0x90, 0xa0, 0x35, 0x26, 0x5a, 0x13, 0xe8, 0x5d, 0x15, 0x59,
	0xb9, 0xcd, 0xf6, 0x33, 0x7a, 0xf7, 0x24, 0x96, 0x3e, 0xee, 0xfb, 0x38, 0xe8, 0x6e, 0x38, 0x6e,
	0xef, 0x25, 0x3b, 0x06, 0x20, 0x23, 0xa3, 0xf6, 0x41, 0xb2, 0x6f, 0x00, 0xb0, 0xc1, 0x98, 0xbd,
	0x87, 0x6c, 0x1f, 0x80, 0x0d, 0x8f, 0xd8, 0xc3, 0xe7, 0x8c, 0x8c, 0xd7, 0xbb, 0xc9, 0xdc, 0x10,
	0x60, 0x60, 0xb4, 0xde, 0x49, 0xb6, 0x0d, 0x9a, 0x51, 0x1d, 0xab, 0x2b, 0x87, 0x8f, 0x1d, 0xa9,
	0x8b, 0x18, 0x75, 0x22, 0x6d, 0xaa, 0x59, 0xf4, 0x09, 0x3b, 0xe1, 0xd9, 0x2f, 0x18, 0x45, 0x16,
	0xe1, 0xa8, 0xb9, 0x95, 0xd0, 0x44, 0x5a, 0xce, 0x5e, 0x2e, 0x9f, 0xb7, 0xb3, 0x1b, 0x76, 0xab,
	0x2c, 0x99, 0xb1, 0x7f, 0xd3, 0xaf, 0x4c, 0xd9, 0xa9, 0x04, 0xd0, 0x1a, 0x89, 0xe4, 0xbc, 0x15,
	0xf0, 0x76, 0x41, 0xe2, 0x5a, 0x3c, 0xd0, 0x40, 0x1f, 0x9d, 0x42, 0xf3, 0xb3, 0xac, 0xc8, 0x26,
	0xff, 0xbc, 0x64, 0xd2, 0x1f, 0x4e, 0x57, 0x2a, 0x69, 0x31, 0x79, 0xe7, 0x6d, 0xc4, 0x87, 0x96,
	0x1d, 0x9a, 0x23, 0x89, 0xc3, 0xda, 0x1c, 0xb9, 0xb4, 0x00, 0x72, 0xd9, 0xce, 0xd2, 0x0a, 0xa7,
	0xb4, 0xaa, 0x24, 0xd3, 0x6f, 0x40, 0xe1, 0x70, 0x56, 0x76, 0xa7, 0x6c, 0x0e, 0xcf, 0xca, 0x6e,
	0x45, 0xf3, 0x7d, 0xd3, 0xec, 0x08, 0x99, 0xdf, 0xc8, 0x84, 0xa2, 0x2f, 0x68, 0x08, 0xb2, 0xb0,
	0xdd, 0x3f, 0xcd, 0x2e, 0x26, 0x24, 0x8a, 0x41, 0xa6, 0x42, 0xeb, 0x04, 0xe8, 0xdb, 0xea, 0x95,
	0xf4, 0xcd, 0xfa, 0x6c, 0x14, 0x86, 0x5c, 0xfa, 0xf4, 0x2f, 0x96, 0x05, 0xdb, 0x02, 0x36, 0x20,
	0xb0, 0x7c, 0x24, 0x4a, 0x0c, 0xf2, 0xff, 0x79, 0x72, 0x70, 0xdc, 0xde, 0x11, 0x02, 0x80, 0x43,
	0x00, 0x36, 0xc7, 0xff, 0x8b, 0xb5, 0xcd, 0x08, 0x27, 0x83, 0x43, 0x64, 0xbf, 0x43, 0x3b, 0x0a,
	0x90, 0x61, 0xf1, 0x3f, 0xc7, 0x3c, 0x6d, 0xa5, 0x79, 0xbc, 0xde, 0xbc, 0xe1, 0xf8, 0xab, 0x97,
	0x4f, 0xad, 0xdd, 0xbc, 0x7e, 0xd3, 0xe1, 0xd7, 0xf6, 0x4f, 0x1f, 0x69, 0xf7, 0xfb, 0xcb, 0x2b,
	0x3d, 0xaf, 0x7f, 0x66, 0xed, 0xc6, 0x53, 0x67, 0x7a, 0xe7, 0x4c, 0xbf, 0xbf, 0xb2, 0x7a, 0x64,
	0xf5, 0xd6, 0x1b, 0x4f, 0x9e, 0xec, 0xaf, 0x9c, 0x38, 0x62, 0xff, 0xb2, 0x73, 0xc4, 0xfe, 0x65,
	0xe7, 0xa6, 0x19, 0xfb, 0x8f, 0xeb, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x5f, 0xad, 0x2e,
	0xfc, 0x19, 0x00, 0x00,
}
