apiVersion: skaffold/v2beta6
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
      env:
      - GOPROXY={{.GOPROXY}}
    sync:
      auto: {}
profiles:
- name: gcb
  build:
    googleCloudBuild: {}
