name: Nightly integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Release binary integration tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install Kustomize
      run: |
        wget -O kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.5.4/kustomize_v3.5.4_linux_amd64.tar.gz
        sudo tar -xvf kustomize.tar.gz -C /usr/local/bin/

    - name: Install Kompose
      run: |
        wget -O kompose https://github.com/kubernetes/kompose/releases/download/v1.21.0/kompose-linux-amd64 && chmod +x kompose
        sudo mv kompose /usr/local/bin/

    - name: Install Ko
      run: |
        (cd && GO111MODULE=on go get github.com/google/ko/cmd/ko)

    - name: Install GCloud and configure
      run: |
        wget -O gcloud.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-276.0.0-linux-x86_64.tar.gz
        sudo tar -xvf gcloud.tar.gz -C /
        sudo CLOUDSDK_PYTHON="python2.7" /google-cloud-sdk/install.sh --usage-reporting=false --bash-completion=false --disable-installation-options
        echo "::add-path::/google-cloud-sdk/bin"
        sudo gcloud auth configure-docker

    - name: Install Container Structure Test
      run: |
        wget -O container-structure-test https://storage.googleapis.com/container-structure-test/v1.8.0/container-structure-test-linux-amd64 && chmod +x container-structure-test
        sudo mv container-structure-test /usr/local/bin/

    - name: Install tools for Minikube None type driver
      run: |
        sudo apt-get update -qq
        sudo apt-get -qq -y install conntrack
        sudo apt-get -qq -y install socat
        VERSION="v1.17.0"
        curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-${VERSION}-linux-amd64.tar.gz --output crictl-${VERSION}-linux-amd64.tar.gz
        sudo tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/local/bin

    - name: Setup other files and permissions
      run: |
        sudo chown $(whoami) /home/$(whoami)/.config/gcloud -R
        sudo chmod g+rw /home/$(whoami)/.config/gcloud -R
        sudo chown $(whoami):docker /home/$(whoami)/.docker -R
        sudo chmod g+rw /home/$(whoami)/.docker -R
        echo '{}' > /home/$(whoami)/.docker/config.json
        mkdir -p /home/$(whoami)/.m2/ && cp ./hack/maven/settings.xml /home/$(whoami)/.m2/settings.xml

    - name: Install Minikube and start cluster
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube /usr/local/bin/minikube
        sudo CHANGE_MINIKUBE_NONE_USER=true minikube start --profile=minikube --driver=docker

    - name: Install Skaffold release binary
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/builds/latest/skaffold-linux-amd64
        sudo install skaffold /usr/local/bin/skaffold


    - name: Run integration tests
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: sudo make integration-tests
